### PR TITLE
cleanup, spaces to tabs, 2.0 test fixes

### PR DESCRIPTION
**Pull request by dereuromark**
lots of cleanup, nothing changed from the functionality so far yet.

### CODE REVIEW

**Comment by torifat** [comment]
Hi can you please reindent your code using my current seetings (4 space indentation) and submit the pull request again :smile:

**Comment by dereuromark** [comment]
nope. sry :)
then you would have to close. tabs is the only correction indentation nowadays. not only for cake itself but also for userland code.

even worse, I think you already had some wild mix of spaces and tabs in there, anyway.

**Comment by torifat** [comment]
`tabs is the only correction indentation nowadays.` this statement can be true for CakePHP world but not for everyone. And, my code messed up due to excepting pull request like this.

BTW, I'm detached from PHP & CakePHP for more than a year. So, Don't know the current trends.

**Comment by torifat** [comment]
Anyway thanks for the pull request :smile:

**Comment by dereuromark** [comment]
I guess I may develop further on it then on my own, am I not? ;) I got your blessing?

**Comment by torifat** [comment]
Yeah, sure! But, Don't think you are alone. There are many awesome developers around :wink: And, I also got help from many of them.

**Pull request merged**
