### PR TITLE
composer, correct html link usage, cs

### PR DESCRIPTION
**Pull request by dereuromark**
Also removed the not working controllerMenu() stuff.
All tests pass.

### CODE REVIEW

**Comment by torifat** [comment]
Thanks guys. Great Job :+1:

**Comment by dereuromark** [comment]
Will you merge 2.0 in master soon? Is there any semvar planned?

**Comment by torifat** [comment]
@dereuromark Yes, I will fix those things tonight. Thanks for the suggestions.

BTW, I used to follow semvar -> https://github.com/torifat/cake-menu_builder/releases

Here, 2.0 means the cakephp version

**Comment by torifat** [comment]
@dereuromark If you want I can add you as a collaborator & as a maintainer in the packagist. Since, I'm not connected with cakephp community for a long time (few years). And, You have already contributed a lot in this project.

**Pull request merged**
